-- =============================================================================
-- 005_machines_expand.sql
-- machines_master 拡張（500機種以上）
--
-- sources: machines.json + store_machines.json + complete_info.json + machines_master.csv
-- ON CONFLICT (official_name) DO NOTHING で冪等
-- normalize_for_comparison() は machine_resolver.py と同一ロジックで生成
-- =============================================================================

INSERT INTO machines_master
    (official_name, manufacturer, brand, type, normalized_name, source_url, is_active)
VALUES
    ('スマスロ北斗の拳転生の章2', 'サミー', NULL, 'slot', '北斗の拳転生の章2', NULL, TRUE),
    ('L革命機ヴァルヴレイヴ2', 'サミー', NULL, 'slot', '革命機ヴァルヴレイヴ2', NULL, TRUE),
    ('L炎炎ノ消防隊2', 'ユニバーサルエンターテインメント', NULL, 'slot', '炎炎ノ消防隊2', NULL, TRUE),
    ('Lミリオンゴッド神々の軌跡', 'ユニバーサルエンターテインメント', NULL, 'slot', 'ミリオンゴッド神々の軌跡', NULL, TRUE),
    ('L甲鉄城のカバネリ海門決戦', 'ビスティ', NULL, 'slot', '甲鉄城のカバネリ海門決戦', NULL, TRUE),
    ('L東京喰種', 'コナミアミューズメント', NULL, 'slot', '東京喰種', NULL, TRUE),
    ('スマスロ北斗の拳', 'サミー', NULL, 'slot', '北斗の拳', NULL, TRUE),
    ('スマスロ攻殻機動隊', 'エレコ', NULL, 'slot', '攻殻機動隊', NULL, TRUE),
    ('バジリスク絆2', 'ユニバーサルエンターテインメント', NULL, 'slot', 'バジリスク絆2', NULL, TRUE),
    ('L真打吉宗', '大都技研', NULL, 'slot', '真打吉宗', NULL, TRUE),
    ('L吉宗', '大都技研', NULL, 'slot', '吉宗', NULL, TRUE),
    ('スマスロゴッドイーター', NULL, NULL, 'slot', 'ゴッドイーター', NULL, TRUE),
    ('L沖ドキDUO アンコール', 'ユニバーサルエンターテインメント', NULL, 'slot', '沖ドキduoアンコール', NULL, TRUE),
    ('Lチバリヨ2ZB', 'ユニバーサルエンターテインメント', NULL, 'slot', 'チバリヨ2zb', NULL, TRUE),
    ('Lシャーマンキング', 'KPE', NULL, 'slot', 'シャーマンキング', NULL, TRUE),
    ('L新鬼武者3', 'コナミアミューズメント', NULL, 'slot', '新鬼武者3', NULL, TRUE),
    ('Lかぐや様は告らせたい', 'KPE', NULL, 'slot', 'かぐや様は告らせたい', NULL, TRUE),
    ('スマスロバイオハザードRE:3', 'エレコ', NULL, 'slot', 'バイオハザードre:3', NULL, TRUE),
    ('Re:ゼロから始める異世界生活', 'ビスティ', NULL, 'slot', 're:ゼロから始める異世界生活', NULL, TRUE),
    ('Lゴジラ', NULL, NULL, 'slot', 'ゴジラ', NULL, TRUE),
    ('Lからくりサーカス', 'パオン・ディーピー', NULL, 'slot', 'からくりサーカス', NULL, TRUE),
    ('L鉄拳6', 'コナミアミューズメント', NULL, 'slot', '鉄拳6', NULL, TRUE),
    ('アイムジャグラーEX', 'ユニバーサルブロス', 'ジャグラー', 'slot', 'アイムジャグラーex', NULL, TRUE),
    ('マイジャグラー5', 'ユニバーサルブロス', 'ジャグラー', 'slot', 'マイジャグラー5', NULL, TRUE),
    ('ファンキージャグラー2', 'ユニバーサルブロス', 'ジャグラー', 'slot', 'ファンキージャグラー2', NULL, TRUE),
    ('ゴーゴージャグラー3', 'ユニバーサルブロス', 'ジャグラー', 'slot', 'ゴーゴージャグラー3', NULL, TRUE),
    ('ハッピージャグラーVⅢ', 'ユニバーサルブロス', 'ジャグラー', 'slot', 'ハッピージャグラーviii', NULL, TRUE),
    ('e牙狼12黄金騎士極限', '三洋物産', NULL, 'pachinko', 'e牙狼12黄金騎士極限', NULL, TRUE),
    ('e牙狼12', '三洋物産', NULL, 'pachinko', 'e牙狼12', NULL, TRUE),
    ('eバイオハザード6', '平和', NULL, 'pachinko', 'eバイオハザード6', NULL, TRUE),
    ('eフィーバーキン肉マン', 'SANKYO', NULL, 'pachinko', 'eフィーバーキン肉マン', NULL, TRUE),
    ('eフィーバーもののがたりF', 'SANKYO', NULL, 'pachinko', 'eフィーバーもののがたりf', NULL, TRUE),
    ('eフィーバーもののがたり', 'SANKYO', NULL, 'pachinko', 'eフィーバーもののがたり', NULL, TRUE),
    ('eひきこまり吸血姫の悶々', NULL, NULL, 'pachinko', 'eひきこまり吸血姫の悶々', NULL, TRUE),
    ('eカケグルイ', '藤商事', NULL, 'pachinko', 'eカケグルイ', NULL, TRUE),
    ('e転生したらスライムだった件2', NULL, NULL, 'pachinko', 'e転生したらスライムだった件2', NULL, TRUE),
    ('スマスロ リコリス・リコイル', NULL, NULL, 'slot', 'リコリス・リコイル', 'https://p-town.dmm.com/machines/5033', TRUE),
    ('Lパチスロ 喰霊-零-Re', NULL, NULL, 'slot', '喰霊-零-re', 'https://p-town.dmm.com/machines/5028', TRUE),
    ('L邪神ちゃんドロップキック', NULL, NULL, 'slot', '邪神ちゃんドロップキック', 'https://p-town.dmm.com/machines/5020', TRUE),
    ('Ｌすーぱぁびん娘', NULL, NULL, 'slot', 'すーぱぁびん娘', 'https://p-town.dmm.com/machines/5038', TRUE),
    ('スマスロ とんでもスキルで異世界放浪メシ', NULL, NULL, 'slot', 'とんでもスキルで異世界放浪メシ', 'https://p-town.dmm.com/machines/5030', TRUE),
    ('Lパチスロ からくりサーカス2', NULL, NULL, 'slot', 'からくりサーカス2', 'https://p-town.dmm.com/machines/5019', TRUE),
    ('スマスロ ケロット5BT', NULL, NULL, 'slot', 'ケロット5bt', 'https://p-town.dmm.com/machines/5015', TRUE),
    ('戦国コレクション6', NULL, NULL, 'slot', '戦国コレクション6', 'https://p-town.dmm.com/machines/5010', TRUE),
    ('L南国育ち SPECIAL', NULL, NULL, 'slot', '南国育ちspecial', 'https://p-town.dmm.com/machines/5031', TRUE),
    ('ローティス', NULL, NULL, 'slot', 'ローティス', 'https://p-town.dmm.com/machines/5029', TRUE),
    ('スマート沖スロ ダークハイビ', NULL, NULL, 'slot', 'スマート沖スロダークハイビ', 'https://p-town.dmm.com/machines/5016', TRUE),
    ('L戦国乙女5 業火を穿つ宿焔の双刃', NULL, NULL, 'slot', '戦国乙女5業火を穿つ宿焔の双刃', 'https://p-town.dmm.com/machines/5009', TRUE),
    ('スロット ソードアート・オンラインⅡ', NULL, NULL, 'slot', 'ソードアート・オンラインii', 'https://p-town.dmm.com/machines/5025', TRUE),
    ('スマスロ BIRDIE WING -Golf Girls'' Story-', NULL, NULL, 'slot', 'birdiewing-golfgirls''story-', 'https://p-town.dmm.com/machines/4996', TRUE),
    ('LB スロット GALFY', NULL, NULL, 'slot', 'bスロットgalfy', 'https://p-town.dmm.com/machines/4992', TRUE),
    ('スマスロスーパーリオエース2', NULL, NULL, 'slot', 'スーパーリオエース2', 'https://p-town.dmm.com/machines/4984', TRUE),
    ('Ｌタクトオーパス デスティニー', NULL, NULL, 'slot', 'タクトオーパスデスティニー', 'https://p-town.dmm.com/machines/5000', TRUE),
    ('スマスロ ビッグドリーム THE GOLDEN PUSHER', NULL, NULL, 'slot', 'ビッグドリームthegoldenpusher', 'https://p-town.dmm.com/machines/4981', TRUE),
    ('アニマルスロット ドッチ', NULL, NULL, 'slot', 'アニマルスロットドッチ', 'https://p-town.dmm.com/machines/4964', TRUE),
    ('Lパチスロ 機動戦士ガンダムユニコーン 覚醒DRIVE', NULL, NULL, 'slot', '機動戦士ガンダムユニコーン覚醒drive', 'https://p-town.dmm.com/machines/5002', TRUE),
    ('スマスロ ミリオンゴッド-神々の軌跡-', NULL, NULL, 'slot', 'ミリオンゴッド-神々の軌跡-', 'https://p-town.dmm.com/machines/4961', TRUE),
    ('Lアクダマドライブ', NULL, NULL, 'slot', 'アクダマドライブ', 'https://p-town.dmm.com/machines/4956', TRUE),
    ('A-SLOT+ 異世界かるてっと BT', NULL, NULL, 'slot', 'a-slot+異世界かるてっとbt', 'https://p-town.dmm.com/machines/4965', TRUE),
    ('L虚構推理', NULL, NULL, 'slot', '虚構推理', 'https://p-town.dmm.com/machines/4973', TRUE),
    ('LBトリプルクラウンセブン', NULL, NULL, 'slot', 'bトリプルクラウンセブン', 'https://p-town.dmm.com/machines/4986', TRUE),
    ('スマスロヨルムンガンド', NULL, NULL, 'slot', 'ヨルムンガンド', 'https://p-town.dmm.com/machines/4970', TRUE),
    ('スマスロ 甲鉄城のカバネリ 海門（うなと）決戦', NULL, NULL, 'slot', '甲鉄城のカバネリ海門(うなと)決戦', 'https://p-town.dmm.com/machines/4930', TRUE),
    ('スマスロ サンダーV', NULL, NULL, 'slot', 'サンダーv', 'https://p-town.dmm.com/machines/4943', TRUE),
    ('Lパチスロうみねこのなく頃に2', NULL, NULL, 'slot', 'うみねこのなく頃に2', 'https://p-town.dmm.com/machines/4925', TRUE),
    ('スマスロ ゴブリンスレイヤーⅡ', NULL, NULL, 'slot', 'ゴブリンスレイヤーii', 'https://p-town.dmm.com/machines/4950', TRUE),
    ('スマスロ ハナビ', NULL, NULL, 'slot', 'ハナビ', 'https://p-town.dmm.com/machines/4928', TRUE),
    ('L範馬刃牙', NULL, NULL, 'slot', '範馬刃牙', 'https://p-town.dmm.com/machines/4941', TRUE),
    ('ニューキングハナハナV-30', NULL, NULL, 'slot', 'ニューキングハナハナv-30', 'https://p-town.dmm.com/machines/4912', TRUE),
    ('スマート沖スロ ニューキングハナハナV', NULL, NULL, 'slot', 'スマート沖スロニューキングハナハナv', 'https://p-town.dmm.com/machines/4911', TRUE),
    ('スマスロ 沖ドキ！DUOアンコール', NULL, NULL, 'slot', '沖ドキ!duoアンコール', 'https://p-town.dmm.com/machines/4906', TRUE),
    ('スマスロ 秘宝伝', NULL, NULL, 'slot', '秘宝伝', 'https://p-town.dmm.com/machines/4929', TRUE),
    ('L不二子BT', NULL, NULL, 'slot', '不二子bt', 'https://p-town.dmm.com/machines/4921', TRUE),
    ('L無職転生～異世界行ったら本気だす～', NULL, NULL, 'slot', '無職転生~異世界行ったら本気だす~', 'https://p-town.dmm.com/machines/4924', TRUE),
    ('銀河英雄伝説 Die Neue These', NULL, NULL, 'slot', '銀河英雄伝説dieneuethese', 'https://p-town.dmm.com/machines/4895', TRUE),
    ('スマスロ 化物語', NULL, NULL, 'slot', '化物語', 'https://p-town.dmm.com/machines/4898', TRUE),
    ('プリズムナナ', NULL, NULL, 'slot', 'プリズムナナ', 'https://p-town.dmm.com/machines/4904', TRUE),
    ('バーニングエクスプレス', NULL, NULL, 'slot', 'バーニングエクスプレス', 'https://p-town.dmm.com/machines/4896', TRUE),
    ('スマスロネオプラネット', NULL, NULL, 'slot', 'ネオプラネット', 'https://p-town.dmm.com/machines/4873', TRUE),
    ('L 絶対衝激Ⅳ', NULL, NULL, 'slot', '絶対衝激iv', 'https://p-town.dmm.com/machines/4903', TRUE),
    ('スマスロ とある科学の超電磁砲2', NULL, NULL, 'slot', 'とある科学の超電磁砲2', 'https://p-town.dmm.com/machines/4892', TRUE),
    ('L 荒野のコトブキ飛行隊', NULL, NULL, 'slot', '荒野のコトブキ飛行隊', 'https://p-town.dmm.com/machines/4891', TRUE),
    ('SHAKE BONUS TRIGGER', NULL, NULL, 'slot', 'shakebonustrigger', 'https://p-town.dmm.com/machines/4893', TRUE),
    ('L主役は銭形5', NULL, NULL, 'slot', '主役は銭形5', 'https://p-town.dmm.com/machines/4877', TRUE),
    ('スマスロ バベル', NULL, NULL, 'slot', 'バベル', 'https://p-town.dmm.com/machines/4853', TRUE),
    ('マジカルハロウィン ボーナストリガー', NULL, NULL, 'slot', 'マジカルハロウィンボーナストリガー', 'https://p-town.dmm.com/machines/4854', TRUE),
    ('クレアの秘宝伝 〜はじまりの扉と太陽の石〜 ボーナストリガーver.', NULL, NULL, 'slot', 'クレアの秘宝伝〜はじまりの扉と太陽の石〜ボーナストリガーver.', 'https://p-town.dmm.com/machines/4860', TRUE),
    ('スマスロ 東京リベンジャーズ', NULL, NULL, 'slot', '東京リベンジャーズ', 'https://p-town.dmm.com/machines/4849', TRUE),
    ('スマスロ ドルアーガの塔', NULL, NULL, 'slot', 'ドルアーガの塔', 'https://p-town.dmm.com/machines/4841', TRUE),
    ('ネオアイムジャグラーEX', NULL, NULL, 'slot', 'ネオアイムジャグラーex', 'https://p-town.dmm.com/machines/4801', TRUE),
    ('L アズールレーン THE ANIMATION', NULL, NULL, 'slot', 'アズールレーンtheanimation', 'https://p-town.dmm.com/machines/4847', TRUE),
    ('L咲-Saki- 頂上決戦', NULL, NULL, 'slot', '咲-saki-頂上決戦', 'https://p-town.dmm.com/machines/4834', TRUE),
    ('L ダーリン・イン・ザ・フランキス', NULL, NULL, 'slot', 'ダーリン・イン・ザ・フランキス', 'https://p-town.dmm.com/machines/4855', TRUE),
    ('パチスロ なめ猫～液晶ないけどなめんじゃねぇ～', NULL, NULL, 'slot', 'なめ猫~液晶ないけどなめんじゃねぇ~', 'https://p-town.dmm.com/machines/4833', TRUE),
    ('マタドールⅢ', NULL, NULL, 'slot', 'マタドールiii', 'https://p-town.dmm.com/machines/4824', TRUE),
    ('アレックス ブライト', NULL, NULL, 'slot', 'アレックスブライト', 'https://p-town.dmm.com/machines/4799', TRUE),
    ('LBパチスロ ヱヴァンゲリヲン ～約束の扉～', NULL, NULL, 'slot', 'bパチスロヱヴァンゲリヲン~約束の扉~', 'https://p-town.dmm.com/machines/4830', TRUE),
    ('LBトリプルクラウン', NULL, NULL, 'slot', 'bトリプルクラウン', 'https://p-town.dmm.com/machines/4831', TRUE),
    ('ハイビリターン-30', NULL, NULL, 'slot', 'ハイビリターン-30', 'https://p-town.dmm.com/machines/4812', TRUE),
    ('わたしの幸せな結婚', NULL, NULL, 'slot', 'わたしの幸せな結婚', 'https://p-town.dmm.com/machines/4803', TRUE),
    ('L 絶対衝激～PLATONIC HEART～', NULL, NULL, 'slot', '絶対衝激~platonicheart~', 'https://p-town.dmm.com/machines/4821', TRUE),
    ('いざ！番長', NULL, NULL, 'slot', 'いざ!番長', 'https://p-town.dmm.com/machines/4805', TRUE),
    ('L ULTRAMAN', NULL, NULL, 'slot', 'ultraman', 'https://p-town.dmm.com/machines/4813', TRUE),
    ('スマスロ ギルティクラウン2', NULL, NULL, 'slot', 'ギルティクラウン2', 'https://p-town.dmm.com/machines/4790', TRUE),
    ('LBジャックポット', NULL, NULL, 'slot', 'bジャックポット', 'https://p-town.dmm.com/machines/4797', TRUE),
    ('LBパチスロ1000ちゃんA', NULL, NULL, 'slot', 'bパチスロ1000ちゃんa', 'https://p-town.dmm.com/machines/4783', TRUE),
    ('スマスロ デビル メイ クライ5 スタイリッシュトライブ', NULL, NULL, 'slot', 'デビルメイクライ5スタイリッシュトライブ', 'https://p-town.dmm.com/machines/4814', TRUE),
    ('翔べ！ハーレムエース', NULL, NULL, 'slot', '翔べ!ハーレムエース', 'https://p-town.dmm.com/machines/4789', TRUE),
    ('スマスロニューパルサーBT', NULL, NULL, 'slot', 'ニューパルサーbt', 'https://p-town.dmm.com/machines/4791', TRUE),
    ('LBプレミアムうまい棒', NULL, NULL, 'slot', 'bプレミアムうまい棒', 'https://p-town.dmm.com/machines/4807', TRUE),
    ('L ToLOVEるダークネス TRANCE ver.8.7', NULL, NULL, 'slot', 'toloveるダークネスtrancever.8.7', 'https://p-town.dmm.com/machines/4806', TRUE),
    ('Lパチスロ 機動戦士ガンダムSEED', NULL, NULL, 'slot', '機動戦士ガンダムseed', 'https://p-town.dmm.com/machines/4788', TRUE),
    ('スマスロ 緑ドン VIVA!情熱南米編 REVIVAL', NULL, NULL, 'slot', '緑ドンviva!情熱南米編revival', 'https://p-town.dmm.com/machines/4763', TRUE),
    ('スマスロ ようこそ実力至上主義の教室へ', NULL, NULL, 'slot', 'ようこそ実力至上主義の教室へ', 'https://p-town.dmm.com/machines/4770', TRUE),
    ('スマスロ アイドルマスター ミリオンライブ！ ネクストプロローグ', NULL, NULL, 'slot', 'アイドルマスターミリオンライブ!ネクストプロローグ', 'https://p-town.dmm.com/machines/4753', TRUE),
    ('L麻雀物語', NULL, NULL, 'slot', '麻雀物語', 'https://p-town.dmm.com/machines/4777', TRUE),
    ('スマート沖スロ アメイジングライブ', NULL, NULL, 'slot', 'スマート沖スロアメイジングライブ', 'https://p-town.dmm.com/machines/4751', TRUE),
    ('Lうしおととら 白面決戦', NULL, NULL, 'slot', 'うしおととら白面決戦', 'https://p-town.dmm.com/machines/4776', TRUE),
    ('スマスロ マギアレコード 魔法少女まどか☆マギカ外伝', NULL, NULL, 'slot', 'マギアレコード魔法少女まどか☆マギカ外伝', 'https://p-town.dmm.com/machines/4745', TRUE),
    ('回胴黙示録カイジ 狂宴', NULL, NULL, 'slot', '回胴黙示録カイジ狂宴', 'https://p-town.dmm.com/machines/4734', TRUE),
    ('L 仮面ライダー電王', NULL, NULL, 'slot', '仮面ライダー電王', 'https://p-town.dmm.com/machines/4756', TRUE),
    ('Sister Quest', NULL, NULL, 'slot', 'sisterquest', 'https://p-town.dmm.com/machines/4741', TRUE),
    ('L 少女☆歌劇 レヴュースタァライト -The SLOT-', NULL, NULL, 'slot', '少女☆歌劇レヴュースタァライト-theslot-', 'https://p-town.dmm.com/machines/4706', TRUE),
    ('てぃだどんどん', NULL, NULL, 'slot', 'てぃだどんどん', 'https://p-town.dmm.com/machines/4757', TRUE),
    ('スマスロ バイオハザード5', NULL, NULL, 'slot', 'バイオハザード5', 'https://p-town.dmm.com/machines/4754', TRUE),
    ('Lパチスロ ありふれた職業で世界最強', NULL, NULL, 'slot', 'ありふれた職業で世界最強', 'https://p-town.dmm.com/machines/4715', TRUE),
    ('スマスロスーパーブラックジャック', NULL, NULL, 'slot', 'スーパーブラックジャック', 'https://p-town.dmm.com/machines/4712', TRUE),
    ('L島娘', NULL, NULL, 'slot', '島娘', 'https://p-town.dmm.com/machines/4727', TRUE),
    ('L パチスロ シン・エヴァンゲリオン', NULL, NULL, 'slot', 'シン・エヴァンゲリオン', 'https://p-town.dmm.com/machines/4730', TRUE),
    ('スマート沖スロ スターハナハナ', NULL, NULL, 'slot', 'スマート沖スロスターハナハナ', 'https://p-town.dmm.com/machines/4701', TRUE),
    ('A-SLOT+ ディスクアップ ULTRAREMIX', NULL, NULL, 'slot', 'a-slot+ディスクアップultraremix', 'https://p-town.dmm.com/machines/4702', TRUE),
    ('七つの魔剣が支配する', NULL, NULL, 'slot', '七つの魔剣が支配する', 'https://p-town.dmm.com/machines/4709', TRUE),
    ('L にゃんこ大戦争 超神速', NULL, NULL, 'slot', 'にゃんこ大戦争超神速', 'https://p-town.dmm.com/machines/4724', TRUE),
    ('L サラリーマン金太郎', NULL, NULL, 'slot', 'サラリーマン金太郎', 'https://p-town.dmm.com/machines/4718', TRUE),
    ('スターハナハナ-30', NULL, NULL, 'slot', 'スターハナハナ-30', 'https://p-town.dmm.com/machines/4680', TRUE),
    ('チバリヨ2プラス', NULL, NULL, 'slot', 'チバリヨ2プラス', 'https://p-town.dmm.com/machines/4717', TRUE),
    ('スマスロ 一方通行 とある魔術の禁書目録', NULL, NULL, 'slot', '一方通行とある魔術の禁書目録', 'https://p-town.dmm.com/machines/4686', TRUE),
    ('Lスーパービンゴネオ', NULL, NULL, 'slot', 'スーパービンゴネオ', 'https://p-town.dmm.com/machines/4675', TRUE),
    ('Lパチスロ ダンベル何キロ持てる？', NULL, NULL, 'slot', 'ダンベル何キロ持てる?', 'https://p-town.dmm.com/machines/4669', TRUE),
    ('Ｌ 犬夜叉2', NULL, NULL, 'slot', '犬夜叉2', 'https://p-town.dmm.com/machines/4690', TRUE),
    ('ウルトラミラクルジャグラー', NULL, NULL, 'slot', 'ウルトラミラクルジャグラー', 'https://p-town.dmm.com/machines/4683', TRUE),
    ('沖ドキ！ゴージャス-30', NULL, NULL, 'slot', '沖ドキ!ゴージャス-30', 'https://p-town.dmm.com/machines/4674', TRUE),
    ('沖ドキ！ゴージャス', NULL, NULL, 'slot', '沖ドキ!ゴージャス', 'https://p-town.dmm.com/machines/4673', TRUE),
    ('スマスロ 聖戦士ダンバイン', NULL, NULL, 'slot', '聖戦士ダンバイン', 'https://p-town.dmm.com/machines/4681', TRUE),
    ('桃太郎電鉄 ～パチスロも定番！～', NULL, NULL, 'slot', '桃太郎電鉄~パチスロも定番!~', 'https://p-town.dmm.com/machines/4666', TRUE),
    ('Lルパン三世 大航海者の秘宝', NULL, NULL, 'slot', 'ルパン三世大航海者の秘宝', 'https://p-town.dmm.com/machines/4689', TRUE),
    ('Lダブルアタック2 withOZS-1000＆RAPHAEL', NULL, NULL, 'slot', 'ダブルアタック2withozs-1000&raphael', 'https://p-town.dmm.com/machines/4643', TRUE),
    ('スマート沖スロ 超華祭', NULL, NULL, 'slot', 'スマート沖スロ超華祭', 'https://p-town.dmm.com/machines/4639', TRUE),
    ('スマスロ モンスターハンターライズ', NULL, NULL, 'slot', 'モンスターハンターライズ', 'https://p-town.dmm.com/machines/4676', TRUE),
    ('L新・必殺仕置人 回胴 CRASH SPEC', NULL, NULL, 'slot', '新・必殺仕置人回胴crashspec', 'https://p-town.dmm.com/machines/4647', TRUE),
    ('スロット Re:ゼロから始める異世界生活 season2', NULL, NULL, 'slot', 're:ゼロから始める異世界生活season2', 'https://p-town.dmm.com/machines/4658', TRUE),
    ('スマスロ頭文字D 2nd', NULL, NULL, 'slot', '頭文字d2nd', 'https://p-town.dmm.com/machines/4635', TRUE),
    ('スマスロ 鬼武者3', NULL, NULL, 'slot', '鬼武者3', 'https://p-town.dmm.com/machines/4640', TRUE),
    ('今日から俺は!! パチスロ編', NULL, NULL, 'slot', '今日から俺は!!パチスロ編', 'https://p-town.dmm.com/machines/4631', TRUE),
    ('L 真・一騎当千', NULL, NULL, 'slot', '真・一騎当千', 'https://p-town.dmm.com/machines/4650', TRUE),
    ('トリプルクラウンフォーユー', NULL, NULL, 'slot', 'トリプルクラウンフォーユー', 'https://p-town.dmm.com/machines/4668', TRUE),
    ('パチスロハイパーラッシュ', NULL, NULL, 'slot', 'ハイパーラッシュ', 'https://p-town.dmm.com/machines/4617', TRUE),
    ('パチスロL黄門ちゃま天', NULL, NULL, 'slot', '黄門ちゃま天', 'https://p-town.dmm.com/machines/4609', TRUE),
    ('Lパチスロ閃乱カグラ2 SHINOVI MASTER', NULL, NULL, 'slot', '閃乱カグラ2shinovimaster', 'https://p-town.dmm.com/machines/4610', TRUE),
    ('スマスロ ゲゲゲの鬼太郎 覚醒', NULL, NULL, 'slot', 'ゲゲゲの鬼太郎覚醒', 'https://p-town.dmm.com/machines/4606', TRUE),
    ('L D4DJ Pachi-Slot Mix', NULL, NULL, 'slot', 'd4djpachi-slotmix', 'https://p-town.dmm.com/machines/4604', TRUE),
    ('スマスロ トロピカーナ', NULL, NULL, 'slot', 'トロピカーナ', 'https://p-town.dmm.com/machines/4595', TRUE),
    ('Lワンパンマン', NULL, NULL, 'slot', 'ワンパンマン', 'https://p-town.dmm.com/machines/4623', TRUE),
    ('スマスロ ゴッドイーター リザレクション', NULL, NULL, 'slot', 'ゴッドイーターリザレクション', 'https://p-town.dmm.com/machines/4602', TRUE),
    ('賞金首Angel', NULL, NULL, 'slot', '賞金首angel', 'https://p-town.dmm.com/machines/4575', TRUE),
    ('スロット ゾンビランドサガ', NULL, NULL, 'slot', 'ゾンビランドサガ', 'https://p-town.dmm.com/machines/4603', TRUE),
    ('ミスタージャグラー', NULL, NULL, 'slot', 'ミスタージャグラー', 'https://p-town.dmm.com/machines/4588', TRUE),
    ('L アカメが斬る！ 2', NULL, NULL, 'slot', 'アカメが斬る!2', 'https://p-town.dmm.com/machines/4597', TRUE),
    ('S ご〜やちゃんぷる〜 25φ', NULL, NULL, 'slot', 'sご〜やちゃんぷる〜25φ', 'https://p-town.dmm.com/machines/4614', TRUE),
    ('S ご〜やちゃんぷる〜 30φ', NULL, NULL, 'slot', 'sご〜やちゃんぷる〜30φ', 'https://p-town.dmm.com/machines/4613', TRUE),
    ('スマスロ真・北斗無双', NULL, NULL, 'slot', '真・北斗無双', 'https://p-town.dmm.com/machines/4577', TRUE),
    ('Lパチスロ戦姫絶唱シンフォギア 正義の歌', NULL, NULL, 'slot', '戦姫絶唱シンフォギア正義の歌', 'https://p-town.dmm.com/machines/4579', TRUE),
    ('バハマ', NULL, NULL, 'slot', 'バハマ', 'https://p-town.dmm.com/machines/4584', TRUE),
    ('沖ドキ！BLACK', NULL, NULL, 'slot', '沖ドキ!black', 'https://p-town.dmm.com/machines/4582', TRUE),
    ('アオハル♪操 A-LIVE', NULL, NULL, 'slot', 'アオハル♪操a-live', 'https://p-town.dmm.com/machines/4581', TRUE),
    ('スマスロ ストリートファイターV 挑戦者の道', NULL, NULL, 'slot', 'ストリートファイターv挑戦者の道', 'https://p-town.dmm.com/machines/4583', TRUE),
    ('L聖闘士星矢 海皇覚醒 CUSTOM EDITION', NULL, NULL, 'slot', '聖闘士星矢海皇覚醒customedition', 'https://p-town.dmm.com/machines/4572', TRUE),
    ('L ToLOVEるダークネス', NULL, NULL, 'slot', 'toloveるダークネス', 'https://p-town.dmm.com/machines/4571', TRUE),
    ('琉金30', NULL, NULL, 'slot', '琉金30', 'https://p-town.dmm.com/machines/4616', TRUE),
    ('Lウルトラマンティガ', NULL, NULL, 'slot', 'ウルトラマンティガ', 'https://p-town.dmm.com/machines/4565', TRUE),
    ('Lパチスロ炎炎ノ消防隊', NULL, NULL, 'slot', '炎炎ノ消防隊', 'https://p-town.dmm.com/machines/4555', TRUE),
    ('沖シーサー-30', NULL, NULL, 'slot', '沖シーサー-30', 'https://p-town.dmm.com/machines/4552', TRUE),
    ('スマスロ交響詩篇エウレカセブン4 HI-EVOLUTION', NULL, NULL, 'slot', '交響詩篇エウレカセブン4hi-evolution', 'https://p-town.dmm.com/machines/4539', TRUE),
    ('ニューパルサーSP4 with 太鼓の達人', NULL, NULL, 'slot', 'ニューパルサーsp4with太鼓の達人', 'https://p-town.dmm.com/machines/4550', TRUE),
    ('押忍！番長4', NULL, NULL, 'slot', '押忍!番長4', 'https://p-town.dmm.com/machines/4553', TRUE),
    ('パチスロ ダンジョンに出会いを求めるのは間違っているだろうか2', NULL, NULL, 'slot', 'ダンジョンに出会いを求めるのは間違っているだろうか2', 'https://p-town.dmm.com/machines/4556', TRUE),
    ('パチスロ金のかぼちゃ', NULL, NULL, 'slot', '金のかぼちゃ', 'https://p-town.dmm.com/machines/4554', TRUE),
    ('Lパチスロうる星やつら', NULL, NULL, 'slot', 'うる星やつら', 'https://p-town.dmm.com/machines/4538', TRUE),
    ('スマスロ ゴールデンカムイ', NULL, NULL, 'slot', 'ゴールデンカムイ', 'https://p-town.dmm.com/machines/4516', TRUE),
    ('ジャグラーガールズSS', NULL, NULL, 'slot', 'ジャグラーガールズss', 'https://p-town.dmm.com/machines/4540', TRUE),
    ('スマスロ ストライク・ザ・ブラッド', NULL, NULL, 'slot', 'ストライク・ザ・ブラッド', 'https://p-town.dmm.com/machines/4547', TRUE),
    ('忍魂参 ～奥義皆伝ノ章～', NULL, NULL, 'slot', '忍魂参~奥義皆伝ノ章~', 'https://p-town.dmm.com/machines/4535', TRUE),
    ('スマート沖スロ ドラゴンハナハナ～閃光～', NULL, NULL, 'slot', 'スマート沖スロドラゴンハナハナ~閃光~', 'https://p-town.dmm.com/machines/4536', TRUE),
    ('ドラゴンハナハナ～閃光～', NULL, NULL, 'slot', 'ドラゴンハナハナ~閃光~', 'https://p-town.dmm.com/machines/4515', TRUE),
    ('SLOT忍者じゃじゃ丸くん', NULL, NULL, 'slot', '忍者じゃじゃ丸くん', 'https://p-town.dmm.com/machines/4525', TRUE),
    ('パチスロ ブラックミクちゃん', NULL, NULL, 'slot', 'ブラックミクちゃん', 'https://p-town.dmm.com/machines/4560', TRUE),
    ('パチスロ ガメラ2', NULL, NULL, 'slot', 'ガメラ2', 'https://p-town.dmm.com/machines/4504', TRUE),
    ('キングクリエーター30', NULL, NULL, 'slot', 'キングクリエーター30', 'https://p-town.dmm.com/machines/4527', TRUE),
    ('スマスロキングパルサー', NULL, NULL, 'slot', 'キングパルサー', 'https://p-town.dmm.com/machines/4511', TRUE),
    ('チバリヨ2', NULL, NULL, 'slot', 'チバリヨ2', 'https://p-town.dmm.com/machines/4530', TRUE),
    ('L南国育ち', NULL, NULL, 'slot', '南国育ち', 'https://p-town.dmm.com/machines/4512', TRUE),
    ('Lパチスロガールズ＆パンツァー 最終章', NULL, NULL, 'slot', 'ガールズ&パンツァー最終章', 'https://p-town.dmm.com/machines/4488', TRUE),
    ('スマスロ コードギアス反逆のルルーシュ／復活のルルーシュ', NULL, NULL, 'slot', 'コードギアス反逆のルルーシュ/復活のルルーシュ', 'https://p-town.dmm.com/machines/4477', TRUE),
    ('L ゴジラ対エヴァンゲリオン', NULL, NULL, 'slot', 'ゴジラ対エヴァンゲリオン', 'https://p-town.dmm.com/machines/4501', TRUE),
    ('スロット 冴えない彼女の育てかた', NULL, NULL, 'slot', '冴えない彼女の育てかた', 'https://p-town.dmm.com/machines/4510', TRUE),
    ('GI優駿倶楽部黄金', NULL, NULL, 'slot', 'gi優駿倶楽部黄金', 'https://p-town.dmm.com/machines/4493', TRUE),
    ('Sky Love', NULL, NULL, 'slot', 'skylove', 'https://p-town.dmm.com/machines/4479', TRUE),
    ('Lストライクウィッチーズ2', NULL, NULL, 'slot', 'ストライクウィッチーズ2', 'https://p-town.dmm.com/machines/4490', TRUE),
    ('ワードオブライツⅡ', NULL, NULL, 'slot', 'ワードオブライツii', 'https://p-town.dmm.com/machines/4494', TRUE),
    ('L 仮面ライダー 7RIDERS', NULL, NULL, 'slot', '仮面ライダー7riders', 'https://p-town.dmm.com/machines/4487', TRUE),
    ('スマスロ バイオハザードヴィレッジ', NULL, NULL, 'slot', 'バイオハザードヴィレッジ', 'https://p-town.dmm.com/machines/4459', TRUE),
    ('パチスロ武装神姫', NULL, NULL, 'slot', '武装神姫', 'https://p-town.dmm.com/machines/4440', TRUE),
    ('Lパチスロ マクロスフロンティア4', NULL, NULL, 'slot', 'マクロスフロンティア4', 'https://p-town.dmm.com/machines/4464', TRUE),
    ('吉宗RISING', NULL, NULL, 'slot', '吉宗rising', 'https://p-town.dmm.com/machines/4478', TRUE),
    ('ドラゴンハナハナ～閃光～ 30', NULL, NULL, 'slot', 'ドラゴンハナハナ~閃光~30', 'https://p-town.dmm.com/machines/4453', TRUE),
    ('スマスロバジリスク～甲賀忍法帖～絆2 天膳 BLACK EDITION', NULL, NULL, 'slot', 'バジリスク~甲賀忍法帖~絆2天膳blackedition', 'https://p-town.dmm.com/machines/4466', TRUE),
    ('Lモンキーターン', NULL, NULL, 'slot', 'モンキーターン', NULL, TRUE),
    ('e東京喰種', NULL, NULL, 'pachinko', 'e東京喰種', NULL, TRUE),
    ('eエヴァ17はじまりR', NULL, NULL, 'pachinko', 'eエヴァ17はじまりr', NULL, TRUE),
    ('eアズールレーン2', NULL, NULL, 'pachinko', 'eアズールレーン2', NULL, TRUE),
    ('e東京喰種W', NULL, NULL, 'pachinko', 'e東京喰種w', NULL, TRUE),
    ('Lビッグドリーム', NULL, NULL, 'slot', 'ビッグドリーム', NULL, TRUE),
    ('L戦国乙女4', NULL, NULL, 'slot', '戦国乙女4', NULL, TRUE),
    ('e新世紀エヴァンゲリオン', NULL, NULL, 'pachinko', 'e新世紀エヴァンゲリオン', NULL, TRUE),
    ('カケグルイ219ver', NULL, NULL, 'slot', 'カケグルイ219ver', NULL, TRUE),
    ('「モンスターハンターライズ」', NULL, NULL, 'slot', '「モンスターハンターライズ」', NULL, TRUE),
    ('eフィーバーブルーロック', NULL, NULL, 'pachinko', 'eフィーバーブルーロック', NULL, TRUE),
    ('LタクトオーパスM1', NULL, NULL, 'slot', 'タクトオーパスm1', NULL, TRUE),
    ('e女神のカフェテラス', NULL, NULL, 'pachinko', 'e女神のカフェテラス', NULL, TRUE),
    ('スマスロ賭ケグルイ', NULL, NULL, 'slot', '賭ケグルイ', NULL, TRUE),
    ('Lアズールレーン2', NULL, NULL, 'slot', 'アズールレーン2', NULL, TRUE),
    ('e北斗の拳 暴凶星', NULL, NULL, 'pachinko', 'e北斗の拳暴凶星', NULL, TRUE),
    ('e花の慶次～黄金の一撃～', NULL, NULL, 'pachinko', 'e花の慶次~黄金の一撃~', NULL, TRUE),
    ('モンキーターンV', NULL, NULL, 'slot', 'モンキーターンv', NULL, TRUE),
    ('eブルーロック', NULL, NULL, 'pachinko', 'eブルーロック', NULL, TRUE),
    ('e炎炎ノ消防隊2', NULL, NULL, 'pachinko', 'e炎炎ノ消防隊2', NULL, TRUE),
    ('Lバンドリ', NULL, NULL, 'slot', 'バンドリ', NULL, TRUE),
    ('ｅリング', NULL, NULL, 'pachinko', 'eリング', NULL, TRUE),
    ('eガールズ＆パンツァー最終章', NULL, NULL, 'pachinko', 'eガールズ&パンツァー最終章', NULL, TRUE),
    ('女神のカフェテラス', NULL, NULL, 'slot', '女神のカフェテラス', NULL, TRUE),
    ('eフィーバー炎炎ノ消防隊', NULL, NULL, 'pachinko', 'eフィーバー炎炎ノ消防隊', NULL, TRUE),
    ('eカケグルイ 7500ver', NULL, NULL, 'pachinko', 'eカケグルイ7500ver', NULL, TRUE),
    ('P化物語 319ver.', NULL, NULL, 'pachinko', 'p化物語319ver.', NULL, TRUE),
    ('P結城友奈は勇者であるGC250Ba', NULL, NULL, 'pachinko', 'p結城友奈は勇者であるgc250ba', NULL, TRUE),
    ('PフィーバークィーンⅡ', NULL, NULL, 'pachinko', 'pフィーバークィーンii', NULL, TRUE),
    ('e範馬刃牙 199ver.', NULL, NULL, 'pachinko', 'e範馬刃牙199ver.', NULL, TRUE),
    ('e東京リベンジャーズ', NULL, NULL, 'pachinko', 'e東京リベンジャーズ', NULL, TRUE),
    ('eようこそ実力至上主義の教室へ', NULL, NULL, 'pachinko', 'eようこそ実力至上主義の教室へ', NULL, TRUE),
    ('Pメイドインアビス 奈落の連環蝕', NULL, NULL, 'pachinko', 'pメイドインアビス奈落の連環蝕', NULL, TRUE),
    ('押忍！番長ZERO', NULL, NULL, 'slot', '押忍!番長zero', NULL, TRUE),
    ('e86-エイティシックス-', NULL, NULL, 'pachinko', 'e86-エイティシックス-', NULL, TRUE),
    ('デカスタP戦国無双100ver.', NULL, NULL, 'pachinko', 'デカスタp戦国無双100ver.', NULL, TRUE),
    ('Pえとたま2 神祭 干支甘', NULL, NULL, 'pachinko', 'pえとたま2神祭干支甘', NULL, TRUE),
    ('e 甲鉄城のカバネリ2 咲かせや燦然', NULL, NULL, 'pachinko', 'e甲鉄城のカバネリ2咲かせや燦然', NULL, TRUE),
    ('eリコリス・リコイル', NULL, NULL, 'pachinko', 'eリコリス・リコイル', NULL, TRUE),
    ('e 終末のワルキューレ', NULL, NULL, 'pachinko', 'e終末のワルキューレ', NULL, TRUE),
    ('Pハネモノ ファミリースタジアム', NULL, NULL, 'pachinko', 'pハネモノファミリースタジアム', NULL, TRUE),
    ('パチスロ 革命機ヴァルヴレイヴ', NULL, NULL, 'slot', '革命機ヴァルヴレイヴ', NULL, TRUE),
    ('L戦国乙女4 戦乱に閃く炯眼の軍師', NULL, NULL, 'slot', '戦国乙女4戦乱に閃く炯眼の軍師', NULL, TRUE),
    ('パチスロ バイオハザード RE:2', NULL, NULL, 'slot', 'バイオハザードre:2', NULL, TRUE),
    ('e 北斗の拳11 暴凶星', NULL, NULL, 'pachinko', 'e北斗の拳11暴凶星', NULL, TRUE),
    ('e一方通行 とある魔術の禁書目録', NULL, NULL, 'pachinko', 'e一方通行とある魔術の禁書目録', NULL, TRUE),
    ('Pフィーバーからくりサーカス', NULL, NULL, 'pachinko', 'pフィーバーからくりサーカス', NULL, TRUE),
    ('Pフィーバーパワフル（2021年）', NULL, NULL, 'pachinko', 'pフィーバーパワフル(2021年)', NULL, TRUE),
    ('e吉宗 極乗3000ver.', NULL, NULL, 'pachinko', 'e吉宗極乗3000ver.', NULL, TRUE),
    ('PA野生の王国Ⅵ', NULL, NULL, 'pachinko', 'pa野生の王国vi', NULL, TRUE),
    ('PA花の慶次 裂 99ver.', NULL, NULL, 'pachinko', 'pa花の慶次裂99ver.', NULL, TRUE),
    ('PLT激デジ ジューシーハニー極嬢', NULL, NULL, 'pachinko', 'plt激デジジューシーハニー極嬢', NULL, TRUE),
    ('e 真・北斗無双 第5章 夢幻闘双', NULL, NULL, 'pachinko', 'e真・北斗無双第5章夢幻闘双', NULL, TRUE),
    ('eアクダマドライブ', NULL, NULL, 'pachinko', 'eアクダマドライブ', NULL, TRUE),
    ('e黄門ちゃま寿限無 LLサイズ', NULL, NULL, 'pachinko', 'e黄門ちゃま寿限無llサイズ', NULL, TRUE),
    ('P愛の不時着', NULL, NULL, 'pachinko', 'p愛の不時着', NULL, TRUE),
    ('P大海物語4スペシャル', NULL, NULL, 'pachinko', 'p大海物語4スペシャル', NULL, TRUE),
    ('PA海物語3R2スペシャル', NULL, NULL, 'pachinko', 'pa海物語3r2スペシャル', NULL, TRUE),
    ('PA海物語3R3', NULL, NULL, 'pachinko', 'pa海物語3r3', NULL, TRUE),
    ('Pラブ嬢 〜極嬢のハーレム体験〜', NULL, NULL, 'pachinko', 'pラブ嬢〜極嬢のハーレム体験〜', NULL, TRUE),
    ('P大海物語5スペシャル', NULL, NULL, 'pachinko', 'p大海物語5スペシャル', NULL, TRUE),
    ('PA激デジ ジューシーハニーハーレム', NULL, NULL, 'pachinko', 'pa激デジジューシーハニーハーレム', NULL, TRUE),
    ('eフィーバーダンベル何キロ持てる？2', NULL, NULL, 'pachinko', 'eフィーバーダンベル何キロ持てる?2', NULL, TRUE),
    ('e地獄少女7500Ver.', NULL, NULL, 'pachinko', 'e地獄少女7500ver.', NULL, TRUE),
    ('HEY！エリートサラリーマン鏡', NULL, NULL, 'slot', 'hey!エリートサラリーマン鏡', NULL, TRUE),
    ('PフィーバークィーンⅡ（2020年）', NULL, NULL, 'pachinko', 'pフィーバークィーンii(2020年)', NULL, TRUE),
    ('eリング 最恐領域', NULL, NULL, 'pachinko', 'eリング最恐領域', NULL, TRUE),
    ('e範馬刃牙', NULL, NULL, 'pachinko', 'e範馬刃牙', NULL, TRUE),
    ('e花の慶次〜黄金の一撃', NULL, NULL, 'pachinko', 'e花の慶次〜黄金の一撃', NULL, TRUE),
    ('e炎炎ノ消防隊2 シンラver.', NULL, NULL, 'slot', 'e炎炎ノ消防隊2シンラver.', NULL, TRUE)
ON CONFLICT (official_name) DO NOTHING;